flush ruleset

table inet filter {
	set icmp4_errors {
		type icmp_type
		elements = { destination-unreachable,
			     time-exceeded,
			     parameter-problem }
	}

	set icmp6_errors {
		type icmpv6_type
		elements = { destination-unreachable,
			     packet-too-big,
			     time-exceeded,
			     parameter-problem }
	}

	set github_ips {
		type ipv4_addr
		flags interval
		elements = { 4.208.26.197, 4.208.26.198,
			     4.225.11.194, 4.225.11.200,
			     4.228.31.145, 4.228.31.150,
			     4.237.22.38, 4.237.22.40,
			     20.26.156.214, 20.26.156.215,
			     20.27.177.113, 20.27.177.118,
			     20.29.134.19, 20.29.134.23,
			     20.87.245.0, 20.87.245.4,
			     20.175.192.146, 20.175.192.147,
			     20.199.39.227, 20.199.39.232,
			     20.200.245.247, 20.200.245.248,
			     20.201.28.151, 20.201.28.152,
			     20.205.243.160, 20.205.243.166,
			     20.207.73.82, 20.207.73.83,
			     20.217.135.4, 20.217.135.5,
			     20.233.83.145, 20.233.83.149,
			     140.82.112.0/20, 143.55.64.0/20,
			     185.199.108.0/22, 192.30.252.0/22 }
	}

	chain ct_base {
		ct state vmap { invalid counter : drop, established counter : accept, related counter : accept }
	}

	chain input {
		type filter hook input priority filter; policy drop;
		jump ct_base
		icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert } counter accept
		icmpv6 type . ip6 saddr { nd-router-advert . fe80::/10, mld-listener-query . fe80::/10 } counter accept
		iif "lo" counter accept
		iif != "lo" ip daddr 127.0.0.0/8 counter drop
		iif != "lo" ip6 daddr ::1 counter drop
		udp sport 67 udp dport 68 counter accept
		icmp type @icmp4_errors limit rate 10/second burst 5 packets counter accept
		icmpv6 type @icmp6_errors limit rate 10/second burst 5 packets counter accept
		ip saddr 192.168.0.0/24 icmp type echo-request counter accept
		icmp type echo-request counter drop
		ip6 saddr fe80::/10 icmpv6 type echo-request counter accept
		icmpv6 type echo-request counter drop
		counter
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
		counter
	}

	chain output {
		type filter hook output priority filter; policy drop;
		jump ct_base
		oif "lo" counter accept
		udp sport 68 udp dport 67 counter accept
		udp dport 123 ip daddr { 162.159.200.1, 162.159.200.123 } counter accept
		tcp dport 853 ip daddr { 9.9.9.9, 149.112.112.112 } counter accept
		tcp dport 22 ip daddr @github_ips counter accept
		tcp dport { 80, 443 } counter accept
		tcp dport { 22, 8006 } ip daddr 192.168.0.10 counter accept
		tcp dport 22 ip daddr 192.168.0.1 counter accept
		icmp type @icmp4_errors limit rate 10/second burst 5 packets counter accept
		icmp type echo-request counter accept
		icmpv6 type @icmp6_errors limit rate 10/second burst 5 packets counter accept
		icmpv6 type { echo-request, mld-listener-report, mld-listener-done, nd-router-solicit, nd-neighbor-solicit, nd-neighbor-advert, mld2-listener-report } counter accept
		counter
	}
}
