#!/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        ct state { established, related } counter accept
        icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert } counter accept
        icmpv6 type nd-router-advert ip6 saddr fe80::/10 counter accept
        ct state invalid counter drop
        iif lo counter accept
        iif != lo ip daddr 127.0.0.1/8 counter drop
        iif != lo ip6 daddr ::1/128 counter drop
        udp sport 67 udp dport 68 counter accept
        icmp type { destination-unreachable, time-exceeded, parameter-problem } limit rate 10/second counter accept
        icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem } limit rate 10/second counter accept
        counter
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        counter
    }

    chain output {
        type filter hook output priority 0; policy drop;
        ct state { established, related } counter accept
        ct state invalid counter drop
        udp sport 68 udp dport 67 counter accept
        tcp dport 853 ip daddr { 9.9.9.9, 149.112.112.112 } counter accept
        tcp dport 853 ip6 daddr { 2620:fe::fe, 2620:fe::9 } counter accept
        tcp dport { 80, 443 } counter accept
        icmp type { destination-unreachable, time-exceeded, parameter-problem } limit rate 10/second counter accept
        ip6 nexthdr icmpv6 icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, nd-router-solicit, nd-neighbor-solicit, nd-neighbor-advert } counter accept
        counter
    }
}
