#!/sbin/nft -f

flush ruleset

table inet filter {
    set icmp4_errors { type icmp_type; elements = { destination-unreachable, time-exceeded, parameter-problem } }
    set icmp6_errors { type icmpv6_type; elements = { destination-unreachable, packet-too-big, time-exceeded, parameter-problem } }

    chain ct_base {
        ct state invalid counter drop
        ct state { established, related } counter accept
    }

    chain input {
        type filter hook input priority 0; policy drop;
        jump ct_base
        icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert } counter accept
        icmpv6 type nd-router-advert ip6 saddr fe80::/10 counter accept
        iif lo counter accept
        iif != lo ip daddr 127.0.0.1/8 counter drop
        iif != lo ip6 daddr ::1/128 counter drop
        udp sport 67 udp dport 68 counter accept
        icmp type @icmp4_errors limit rate 10/second counter accept
        icmpv6 type @icmp6_errors limit rate 10/second counter accept
        counter
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        counter
    }

    chain output {
        type filter hook output priority 0; policy drop;
        jump ct_base
        oif lo counter accept
        udp sport 68 udp dport 67 counter accept
        udp dport 123 ip daddr { 162.159.200.123, 162.159.200.1 } counter accept
        tcp dport 853 ip daddr { 9.9.9.9, 149.112.112.112 } counter accept
        tcp dport { 80, 443 } counter accept
        icmp type @icmp4_errors limit rate 10/second counter accept
        icmpv6 type @icmp6_errors counter accept
        icmpv6 type { nd-router-solicit, nd-neighbor-solicit, nd-neighbor-advert } counter accept
        counter
    }
}
